commerce_fondy.commerce_payment_gateway.plugin.fondy:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant ID'
    private_key:
      type: string
      label: 'Private API Key'
    cards_payment_method.cards_payment_status:
      type: string
      label: 'Status'
      default: yes
      class: '\Drupal\Core\TypedData\Plugin\DataType\BooleanData'
    cards_payment_method.cards_payment_title:
      type: string
      label: 'Title'
    title:
      type: string
      label: 'Payment method title'
    bank_links_payment_method.cards_payment_status:
      type: string
      label: 'Status'
    bank_links_payment_method.cards_payment_title:
      type: string
      label: 'Title'
      default: no
      class: '\Drupal\Core\TypedData\Plugin\DataType\BooleanData'
    bank_links_payment_method.bank_links_default_country:
      type: string
      label: 'Default Country'
    bank_links_payment_method.bank_links_allowed_countries:
      type: string
      label: 'Allowed Countries'
    wallets_payment_method.wallets_payment_status:
      type: string
      label: 'Status'
      default: no
      class: '\Drupal\Core\TypedData\Plugin\DataType\BooleanData'
    wallets_payment_method.wallets_payment_title:
      type: string
      label: 'Title'
    enable_preauth:
      type: string
      label: 'Enable Preauth'
      default: no
    payment_type:
      type: string
      label: 'Payment Type'
    order_status_pending:
      type: string
      label: 'Order status after payment'
      default: 'pending'
    order_status_if_canceled:
      type: string
      label: 'Order status if canceled'
      default: 'canceled'
    order_status_in_progress:
      type: string
      label: 'Order status while in progress'
      default: 'progress'

